name = "AdmissibleCarry"
version = "0.1.0"
keywords = ["math", "additive-combinatorics", "number-theory"]
defaultTargets = ["AdmissibleCarry"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0-rc2"

[[lean_lib]]
name = "AdmissibleCarry"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
